### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by wendylw** [jackcylin/hiko-social-login-react#1]
## Environment

node: v18.20.3
 "@shopify/cli": "3.59.2",
 "@types/react": "^18.2.22",

## Error
ReferenceError: module is not defined
    at /Users/wendylin/shopify/luxerose-storefront/node_modules/hiko-social-login-react/dist/index.js:26:1
    at Object.runViteModule (Users/test/shopify/storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1181:17)
    at ViteRuntime.directRequest (Users/test/shopify/storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1026:78)
    at ViteRuntime.cachedRequest (Users/test/shopify/storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:949:28)
    at request (Users/test/shopify/storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:976:128)
    at /app/components/SignIn/index.tsx:3:31
    at Object.runViteModule (Users/test/shopify/storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1181:11)
    at ViteRuntime.directRequest (Users/test/shopify/storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1026:60)
    at ViteRuntime.cachedRequest (Users/test/shopify/storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:950:79)
    at /app/components/Layout.tsx:6:31

### vite.config.ts
	import {defineConfig} from 'vite';
	import {hydrogen} from '@shopify/hydrogen/vite';
	import {oxygen} from '@shopify/mini-oxygen/vite';
	import {vitePlugin as remix} from '@remix-run/dev';
	import tsconfigPaths from 'vite-tsconfig-paths';
	import commonjs from 'vite-plugin-commonjs';
	
	export default defineConfig({
	  plugins: [
	    hydrogen(),
	    oxygen(),
	    remix({
	      presets: [hydrogen.preset()],
	      future: {
	        v3_fetcherPersist: true,
	        v3_relativeSplatPath: true,
	        v3_throwAbortReason: true,
	      },
	    }),
	    tsconfigPaths(),
	    commonjs(), // Add the Rollup CommonJS plugin
	  ],
	  build: {
	    assetsInlineLimit: 0,
	    commonjsOptions: {
	      include: [/node_modules/, /hiko-social-login-react/], // Ensure CommonJS modules are handled
	    },
	  },
	  server: {
	    hmr: {
	      overlay: false,
	    },
	  },
	  optimizeDeps: {
	    include: ['hiko-social-login-react'],
	  },
	});

### tsconfig.json

	{
	  "include": ["./**/*.d.ts", "./**/*.ts", "./**/*.tsx"],
	  "compilerOptions": {
	    "lib": ["DOM", "DOM.Iterable", "ES2022"],
	    "isolatedModules": true,
	    "esModuleInterop": true,
	    "jsx": "react-jsx",
	    "moduleResolution": "Bundler",
	    "resolveJsonModule": true,
	    "module": "ES2022",
	    "target": "ES2022",
	    "strict": true,
	    "allowJs": true,
	    "forceConsistentCasingInFileNames": true,
	    "skipLibCheck": true,
	    "baseUrl": ".",
	    "types": ["@shopify/oxygen-workers-types"],
	    "paths": {
	      "~/*": ["app/*"]
	    },
	    "noEmit": true
	  }
	}

How to fix this issue?

**Comment by aswanth-updot** [comment]
Hi
Did you find a solution for this?
